### ISSUE TITLE
Paste doesn't work

### ISSUE THREAD

**Issue by jcubic** [schemeorg/try.scheme.org#7]
I've just wanted to copy/paste some code into an interpreter and it's blocked.
If you have a lot of code no one will retype the code to test it.

**Comment by arthurgleckler** [comment]
It works fine for me in Chrome under Linux.  The C-v shortcut doesn't work, but pasting through the mouse menu works fine.

**Comment by lassik** [comment]
Pasting via Command-V works for me on Mac.

**Comment by jcubic** [comment]
@arthurgleckler note that most users expect CTRL+V to work, using the context menu is an alternative. I expect both to work.

**Comment by feeley** [comment]
Sorry... posted in wrong issue...

**Comment by arthurgleckler** [comment]
On Mon, Oct 17, 2022 at 2:22 PM Marc Feeley ***@***.***>
wrote:

> Do you have any suggestions on the look before I continue working on the
> other sections? Would anyone care to help out with writing the other
> sections that are just HTML? The "run" buttons simply have anonclick
> handler that sends commands to the REPL. For example:
>
It looks truly fantastic.  This is exactly the kind of thing that Scheme
needs to keep the interest of potential new users.  The bar is so much
higher these days than ever before.

My one suggestion is to implement C-v paste so that users don't have to use
the mouse to paste new code in.

**Comment by lassik** [comment]
> The bar is so much higher these days than ever before.

Not to worry. As long as code is represented as trees, Lisp will win in the end. The meta-programming features will make sure of that. The only thing which can unseat Lisp's dominance is if the industry switches the standard code representation from trees to more general graphs. But it hasn't even got rid of text files yet, and Lisp is the ideal vehicle for taking that step.

**Comment by feeley** [comment]
The thing about Ctrl-V is that it is part of the emacs keybindings (page down) that are used by the editors.  Here's part of the new documentation.  I could disable the emacs Ctrl-V /Ctrl-X on Windows and map them to clipboard operations, but I'm not sure how to detect the OS.  Also Ctrl-C is used to interrupt execution (like on the desktop)... what should the keybinding be for this to not interfere with the Windows Ctrl-C (copy to clipboard)?

<img width="410" alt="image" src="https://user-images.githubusercontent.com/555673/196670832-f1d21897-f96a-40bc-bc4e-6d0b8c29bd83.png">

**Comment by jcubic** [comment]
I don't think it's a good idea to use Emacs keybinding for a tutorial about Scheme. This is mainly for people who have no idea what lisp is.

In my Terminal, I use CTRL+D for the interruption (like in Bash to mark end of file) and use CTRL+C and CTRL+V for copy/pasting this is what users expect. No one expects Emacs keys on the web, unless you have web-based Emacs.

**Comment by feeley** [comment]
On the web browsers I use everyday on macOS (Safari, Firefox, Chrome) the basic emacs keybindings work by default in `textarea` elements (ctrl-a for beginning of line, ctrl-k to kill line, etc).  This includes ctrl-V that causes the cursor to go forward one page. So at least for me this is the expected behavior and I rely on it constantly to edit input on web pages (including at this very moment to write this reply!).  The emacs keybindings also work by default on macOS on other developer tools like the Microsoft Visual Studio Code.  Moreover, developer tools such as the shell use emacs keybindings on linux and also on Windows when wsl is started.

Given the historical link between emacs usage and Lisp/Scheme and also that Scheme interpreters are often started from the shell, I think it is a good idea to use the emacs keybindings for the online environment to give a similar "feel" as using a Scheme interpreter from the shell.

I agree that ctrl-V, ctrl-X, ctrl-C are a special case because it will confuse newcomers on Windows and linux where these are the clipboard operations (except in the shell!).  I don't mind mapping ctrl-V and ctrl-X to clipboard paste and cut, but what to do about ctrl-C which is typically used in Scheme interpreters to stop the execution? ctrl-D is not an option because at the REPL it is used for end-of-file and "delete next char" (once again to imitate a Scheme interpreter started from the shell).

**Comment by feeley** [comment]
What about this handling of ctrl-C: treat it as "interrupt execution" when nothing is selected, and as "copy" when something is selected. At least on Safari it seems that when nothing is selected a "copy" does not change the clipboard (i.e. it is a noop).

**Comment by lassik** [comment]
IIRC Ctrl-Z stops a running program on the DOS and Windows command line. But it conflicts with "Undo"...

Note that GNU Emacs comes with `cua-mode` which enables standard cut/copy/paste behavior using Ctrl-X/C/V.

**Comment by feeley** [comment]
What does "cua" mean?

Concerning Ctrl-Z, don't you mean "DOS and Windows use Ctrl-Z to send an EOF to the stdin of the program"? On Windows as well as linux/macOS the Gambit interpreter's REPL handles Ctrl-D as delete next char or EOF on empty line (like the GNU `readline` lib and bash, etc).  The "undo" operation is mapped to both Ctrl-_ (the emacs keybinding) and Ctrl-Z.

**Comment by lassik** [comment]
> What does "cua" mean?

Common User Access ([Wikipedia](https://en.wikipedia.org/wiki/IBM_Common_User_Access), [Emacs manual](https://www.gnu.org/software/emacs/manual/html_node/emacs/CUA-Bindings.html)). Apparently these bindins came from IBM before Microsoft made them ubiquitous.

> Concerning Ctrl-Z, don't you mean "DOS and Windows use Ctrl-Z to send an EOF to the stdin of the program"?

Yes, probably the same feature.

> On Windows as well as linux/macOS the Gambit interpreter's REPL handles Ctrl-D as delete next char or EOF on empty line (like the GNU `readline` lib and bash, etc).

Using Ctrl-D as interrupt when REPL input is empty seems resonable to me (but not sure whether I'm a representative user).

**Comment by feeley** [comment]
I think we're not talking about the same concept... to me a "user interrupt" is when you have a long-running program (or infinite loop) that you want to stop.  This is typically done with Ctrl-C at the console (on most OS's this terminates the current process but Gambit starts a nested REPL).

Ctrl-D at the console is a way to cause an EOF on stdin, which is typically the REPL input.  On Chicken, ChezScheme and Gambit a Ctrl-D at the REPL will cause an EOF to be read so `read` will return the "end-of-file" object `#!eof`:

```
$ csi -q
#;1> (read) ;; at the end of this line I press <enter> then ctrl-D
#!eof
#;2> 
$ chez
Chez Scheme Version 9.5.8
Copyright 1984-2022 Cisco Systems, Inc.

> (read) ;; at the end of this line I press <enter> then ctrl-D
#!eof
> (exit)
$ gsi -
> (read) ;; at the end of this line I press <enter> then ctrl-D
#!eof
> (exit)
```

This is not the same thing as interrupting the current process with Ctrl-C:

```
$ gsi -
> (let loop () (loop)) ;; at the end of this line I press <enter> then ctrl-C
*** INTERRUPTED IN (stdin)@1.1
1> 
```

**Comment by lassik** [comment]
I agree about those meanings.

If you have a long-running program that reads from stdin, is it necessary to be able to differentiate between EOF and interrupt? It probably is. I didn't think of that.

If it's not necessary, then Ctrl-D could serve both purposes. OTOH, Ctrl-C could also probably serve both purposes. If there's no REPL prompt active (or the text selection is empty), it could cause an interrupt.

**Comment by feeley** [comment]
I made some changes to the UI and I believe it should fix the problem with Ctrl-V.  The UI is now up on try.scheme.org .  Please check as I don't have a Windows machine.

**Comment by arthurgleckler** [comment]
C-v works great for me now.  Thanks!
